@extends('errors.layout')
@section('title', 'Akses Ditolak')
@section('code', '403')
@section('message', 'Akses Terlarang')
@section('description', 'Anda tidak memiliki otorisasi untuk mengakses halaman atau mengubah data ini.')
